- name: Hello World
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!!!"
        
    - name: Ansible version
      debug:
        msg: "Ansible version is  {{ ansible_version.full }}"
     
    
