---
- name: Configure IOS-XR devices
  hosts: routers
  gather_facts: no
  connection: network_cli
  vars_files:
    - "{{ playbook_dir }}/../vars/main.yml"

  vars:
    project_dir: "{{ playbook_dir }}/.."
    backup_root: ./backups
    cli:
      host: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_ssh_pass }}"

  roles:
    - hostnames
